/*
account.go
Created at 09.04.22 by emrearmagan
Copyright © go-social. All rights reserved.
*/

package spotify

import (
	"go-social/social"
	"go-social/social/oauth/oauth2"
)

const (
	RefreshBase = "https://accounts.spotify.com"
	RefreshPath = "/api/token/"
)

// AccountService provides methods for user credentials
type AccountService struct {
	oauth2 *oauth2.OAuth2
}

// newAccountService returns a new Reddit UserService.
func newAccountService(oauth2 *oauth2.OAuth2) *AccountService {
	return &AccountService{
		oauth2: oauth2,
	}
}

// RefreshToken a new access token can be generated by supplzing the refresh token originally obtained during
// authorization code exchange.
// https://developer.spotify.com/documentation/general/guides/authorization-guide/
func (a *AccountService) RefreshToken() (*oauth2.OAuthRefreshResponse, error) {
	oauthResp := new(OAuth2Response)
	apiError := new(APIError)

	err := a.oauth2.RefreshToken(RefreshBase, RefreshPath, oauthResp, apiError)
	a.oauth2.UpdateToken(oauth2.NewToken(oauthResp.AccessToken, a.oauth2.Token().RefreshToken))
	return &oauth2.OAuthRefreshResponse{
		Token: oauth2.Token{
			Token:        oauthResp.AccessToken,
			RefreshToken: a.oauth2.Token().RefreshToken,
		},
		TokenType: oauthResp.TokenType,
		ExpiresIn: oauthResp.ExpiresIn,
		Scope:     oauthResp.Scope,
	}, social.CheckError(err)
}
