/*
spotify.go
Created at 09.04.22 by emrearmagan
Copyright © go-social. All rights reserved.
*/

package spotify

import (
	"context"
	"github.com/emrearmagan/go-social/models"
	"github.com/emrearmagan/go-social/oauth"
	"github.com/emrearmagan/go-social/oauth/oauth2"
	"github.com/emrearmagan/go-social/social"
	"github.com/emrearmagan/go-social/social/client"
	"strings"
)

const (
	Base = "https://api.spotify.com/"

	RefreshBase = "https://accounts.spotify.com"
	RefreshPath = "/api/token/"
)

type Client struct {
	oauth2 *oauth2.OAuth2

	User     *UserService
	Playlist *PlaylistService
	Follower *FollowerService
}

// NewClient returns a new Spotify Client.
func NewClient(ctx context.Context, c *oauth.Credentials, token *oauth2.Token) *Client {
	cl := client.NewHttpClient().Base(Base)
	auther := oauth2.NewOAuth(ctx, c, token, cl)

	return &Client{
		oauth2:   auther,
		User:     newUserService(auther),
		Playlist: newPlaylistService(auther),
		Follower: newFollowerService(auther),
	}
}

// RefreshToken a new access token can be generated by supplying the refresh token originally obtained during
// authorization code exchange.
// https://developer.spotify.com/documentation/general/guides/authorization-guide/
func (c *Client) RefreshToken() (*oauth2.OAuthRefreshResponse, error) {
	oauthResp := new(OAuth2Response)
	apiError := new(RefreshError)

	// Spotify requires the basic authentication for refreshing a token, but the bearer authentication for everything else. Yes I don't get it either
	a := c.oauth2.New().Basic()
	err := a.RefreshToken(RefreshBase, RefreshPath, oauthResp, apiError)
	c.oauth2.UpdateToken(oauth2.NewToken(oauthResp.AccessToken, c.oauth2.Token().RefreshToken))
	return &oauth2.OAuthRefreshResponse{
		Token: oauth2.Token{
			Token:        oauthResp.AccessToken,
			RefreshToken: c.oauth2.Token().RefreshToken,
		},
		TokenType: oauthResp.TokenType,
		ExpiresIn: oauthResp.ExpiresIn,
		Scope:     strings.Fields(oauthResp.Scope),
	}, social.CheckError(err)
}

type OAuth2Response struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
	ExpiresIn   int    `json:"expires_in"`
	Scope       string `json:"scope"`
}

func (s *Client) GoSocialUser() (*models.SocialUser, error) {
	p, err := s.Playlist.UserPlaylists(nil)
	if err != nil {
		return nil, err
	}

	f, err := s.Follower.Following(&FollowingParams{
		Type: "artist",
	})
	if err != nil {
		return nil, err
	}

	u, err := s.User.UserCredentials()
	if err != nil {
		return nil, err
	}

	avatarUrl := ""
	if len(u.Images) > 0 {
		avatarUrl = u.Images[0].URL
	}
	goSocial := models.SocialUser{
		Username:     u.DisplayName,
		Name:         u.DisplayName,
		UserId:       u.ID,
		Verified:     strings.ToLower(u.Product) == "premium",
		ContentCount: int64(p.Total),
		Following:    &f.Artists.Total,
		AvatarUrl:    avatarUrl,
		Followers:    u.Followers.Total,
		Url:          u.ExternalUrls.Spotify,
	}

	return &goSocial, nil
}
