/*
spotify.go
Created at 09.04.22 by emrearmagan
Copyright © go-social. All rights reserved.
*/

package spotify

import (
	"github.com/emrearmagan/go-social/models"
	"github.com/emrearmagan/go-social/oauth/oauth2"
	"github.com/emrearmagan/go-social/social"
	"strings"
)

const (
	Base                = "https://api.spotify.com/"
	AuthorizationPrefix = "Bearer " // trailing space is required

	RefreshBase = "https://accounts.spotify.com"
	RefreshPath = "/api/token/"
)

type Client struct {
	oauth2 *oauth2.OAuth2

	User     *UserService
	Playlist *PlaylistService
	Follower *FollowerService
}

// NewClient returns a new Spotify Client.
func NewClient(oauth *oauth2.OAuth2) *Client {
	oauth = oauth.NewClient(oauth.Client().Base(Base))
	oauth.AuthorizationPrefix = AuthorizationPrefix
	return &Client{
		oauth2:   oauth,
		User:     newUserService(oauth),
		Playlist: newPlaylistService(oauth),
		Follower: newFollowerService(oauth),
	}
}

// RefreshToken a new access token can be generated by supplying the refresh token originally obtained during
// authorization code exchange.
// https://developer.spotify.com/documentation/general/guides/authorization-guide/
func (c *Client) RefreshToken() (*oauth2.OAuthRefreshResponse, error) {
	oauthResp := new(OAuth2Response)
	apiError := new(APIError)

	err := c.oauth2.RefreshToken(RefreshBase, RefreshPath, oauthResp, apiError)
	c.oauth2.UpdateToken(oauth2.NewToken(oauthResp.AccessToken, c.oauth2.Token().RefreshToken))
	return &oauth2.OAuthRefreshResponse{
		Token: oauth2.Token{
			Token:        oauthResp.AccessToken,
			RefreshToken: c.oauth2.Token().RefreshToken,
		},
		TokenType: oauthResp.TokenType,
		ExpiresIn: oauthResp.ExpiresIn,
		Scope:     strings.Fields(oauthResp.Scope),
	}, social.CheckError(err)
}

type OAuth2Response struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
	ExpiresIn   int    `json:"expires_in"`
	Scope       string `json:"scope"`
}

func (s *Client) GoSocialUser() (*models.SocialUser, error) {
	p, err := s.Playlist.UserPlaylists(nil)
	if err != nil {
		return nil, err
	}

	f, err := s.Follower.Following(&FollowingParams{
		Type: "artist",
	})
	if err != nil {
		return nil, err
	}

	u, err := s.User.UserCredentials()
	if err != nil {
		return nil, err
	}

	avatarUrl := ""
	if len(u.Images) > 0 {
		avatarUrl = u.Images[0].URL
	}
	goSocial := models.SocialUser{
		Username:     u.DisplayName,
		Name:         u.DisplayName,
		UserId:       u.ID,
		Verified:     strings.ToLower(u.Product) == "premium",
		ContentCount: int64(p.Total),
		Following:    &f.Artists.Total,
		AvatarUrl:    avatarUrl,
		Followers:    u.Followers.Total,
		Url:          u.ExternalUrls.Spotify,
	}

	return &goSocial, nil
}
